version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    working_directory: potter-db/frontend
    docker:
      - image: cimg/node:14.13.0     
    steps:
      - checkout:
          path: potter-db/frontend    
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test